export const GAME_CONFIG = Object.freeze({
  city: {
    halfSize: 330,
    roadWidth: 20,
    roadCenters: [-280, -210, -140, -70, 0, 70, 140, 210, 280],
    boundaryPadding: 4,
  },
  player: {
    maxForwardSpeed: 31,
    maxReverseSpeed: 10,
    acceleration: 17.5,
    reverseAcceleration: 9.5,
    brakeForce: 32,
    steeringRate: 1.62,
    steeringFullSpeed: 6.0,
    highSpeedSteerFactor: 0.56,
    minSteerSpeed: 0.45,
    grip: 8.4,
    handbrakeGrip: 1.75,
    handbrakeTurnBoost: 1.28,
    handbrakeDrag: 1.0,
    rollingResistance: 0.34,
    aerodynamicDrag: 0.017,
    stopSpeed: 0.16,
    reverseEngageSpeed: 0.9,
    collisionRestitution: 0.08,
    collisionRadius: 1.45,
    width: 1.85,
    length: 4.2,
    spawn: { x: 0, z: 210, heading: 0 },
  },
  police: {
    maxSpeed: 29,
    acceleration: 15.5,
    brakeForce: 27,
    steeringRate: 1.48,
    steeringFullSpeed: 5.5,
    highSpeedSteerFactor: 0.62,
    minSteerSpeed: 0.4,
    grip: 9.6,
    rollingResistance: 0.32,
    aerodynamicDrag: 0.016,
    stopSpeed: 0.14,
    collisionRadius: 1.5,
    waypointRadius: 6.5,
    detectionRange: 145,
    loseSightRange: 185,
    searchDuration: 7,
    interceptLeadSeconds: 1.35,
    repathInterval: 0.55,
    spawn: { x: 0, z: 0, heading: Math.PI },
  },
  wanted: {
    levels: [
      { level: 1, label: 'NÍVEL 1', minTime: 0,   starCount: 1, policeCount: 1,  speedMultiplier: 1.00, roadblocks: 0, roadblockRefresh: 999, helicopter: false, maximum: false },
      { level: 2, label: 'NÍVEL 2', minTime: 30,  starCount: 2, policeCount: 3,  speedMultiplier: 1.04, roadblocks: 0, roadblockRefresh: 999, helicopter: false, maximum: false },
      { level: 3, label: 'NÍVEL 3', minTime: 60,  starCount: 3, policeCount: 5,  speedMultiplier: 1.07, roadblocks: 0, roadblockRefresh: 999, helicopter: false, maximum: false },
      { level: 4, label: 'NÍVEL 4', minTime: 120, starCount: 4, policeCount: 6,  speedMultiplier: 1.10, roadblocks: 1, roadblockRefresh: 28,  helicopter: false, maximum: false },
      { level: 5, label: 'NÍVEL 5', minTime: 240, starCount: 5, policeCount: 8,  speedMultiplier: 1.13, roadblocks: 1, roadblockRefresh: 23,  helicopter: false, maximum: false },
      { level: 6, label: 'NÍVEL 6', minTime: 360, starCount: 6, policeCount: 10, speedMultiplier: 1.16, roadblocks: 2, roadblockRefresh: 18,  helicopter: true,  maximum: false },
      { level: 7, label: 'MÁXIMO',  minTime: 600, starCount: 6, policeCount: 12, speedMultiplier: 1.19, roadblocks: 3, roadblockRefresh: 14,  helicopter: true,  maximum: true  },
    ],
    dispatchInterval: 2.5,
    spawnMinDistance: 78,
    spawnMaxDistance: 270,
  },
  combo: {
    maxMultiplier: 5.0,
    nearbyRadius: 42,
    closeRadius: 22,
    riseSharpness: 0.72,
    decaySharpness: 1.25,
    collisionRetention: 0.28,
  },
  capture: {
    pressureRadius: 24,
    sectorCount: 8,
    escapeSpeedKmh: 34,
    fastEscapeSpeedKmh: 68,
    captureThreshold: 0.42,
    minCaptureRate: 5.5,
    maxCaptureRate: 27,
    baseDecayRate: 11,
    speedDecayBonus: 14,
  },
  score: {
    basePointsPerSecond: 10,
    multipliers: {
      1: 1.0,
      2: 1.2,
      3: 1.5,
      4: 2.0,
      5: 2.5,
      6: 3.0,
      7: 3.0,
    },
    bonuses: {
      unitEvaded: 100,
      roadblockAvoided: 200,
      allPoliceEvaded: 300,
      extremeSurvived: 500,
    },
  },

  damage: {
    pole: 3,
    civilianCar: 5,
    policeCar: 8,
    wall: 6,
    highSpeedWall: 15,
    highSpeedWallThresholdKmh: 78,
    heavyObject: 7,
    roadblock: 10,
    other: 4,
    criticalIntegrity: 25,
    performance: {
      minMaxSpeedFactor: 0.58,
      minAccelerationFactor: 0.62,
      minSteeringFactor: 0.76,
    },
  },
  traffic: {
    vehicleCount: 42,
    laneOffset: 3.2,
    waypointRadius: 5.2,
    acceleration: 8.2,
    brakeForce: 15.5,
    steeringRate: 1.15,
    grip: 10.5,
    rollingResistance: 0.22,
    followDistance: 15,
  },
  events: {
    initialDelay: 16,
    intervalMin: 27,
    intervalMax: 40,
    maxActive: 2,
    accidentDuration: 24,
    roadworksDuration: 32,
    heavyTrafficDuration: 28,
    heavyTrafficRadius: 62,
    heavyTrafficSpeedFactor: 0.48,
  },
  powerUps: {
    pickupRadius: 3.6,
    respawnDelay: 15,
    repairAmount: 25,
    nitroDuration: 6,
    nitroSpeedMultiplier: 1.24,
    nitroAccelerationMultiplier: 1.34,
    jammerDuration: 7,
    cashPoints: 650,
  },
  progression: {
    levelThresholds: [0, 800, 2000, 3800, 6200, 9500],
    rewards: {
      minXp: 80,
      minCash: 60,
      xpPerSecond: 3.0,
      xpPerScorePoint: 0.08,
      xpPerWantedLevel: 80,
      cashPerSecond: 1.5,
      cashPerScorePoint: 0.025,
      cashPerWantedLevel: 30,
    },
  },
  camera: {
    distance: 9.5,
    height: 4.8,
    lookAhead: 5.0,
    positionSharpness: 5.5,
    lookSharpness: 7.0,
  },
});
